name = "vile_characher_theme"
license = "GNU General Public License v3.0"
licenselink = "https://github.com/woailuoli993/vile_characher_theme/blob/master/LICENSE"
description = "A Hogo theme fork from kakawait"
homepage = "https://github.com/woailuoli993/vile_characher_theme"
tags = ["blog", "minimal", "responsive", "personal", "customizable", "creative", "fontawesome", "highlight.js"]
features = ["blog", "themes", "disqus", "minimal", "responsive", "font awesome", "highlight.js"]
min_version = 0.20

[author]
  name = "woailuoli993"
  homepage = "https://github.com/woailuoli993"

[original]
  name = "vile_characher_theme"
  homepage = "https://github.com/woailuoli993/vile_characher_theme"
  repo = "https://github.com/woailuoli993/vile_characher_theme"
